name: Build proxy docker image
on:
  workflow_dispatch:
    inputs:
      test_set:
        default: "basic"
        required: true
      neon_evm_commit:
        required: false
      neon_evm_branch:
        required: false
      initial_pr:
        required: false
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, ready_for_review]
  push:
    branches:
      - master
      - develop
      - '[vt][0-9].[0-9]+.[0-9x]+*'
    tags:
      - "*"
env:
  NEON_EVM_TAG: "latest"
  FAUCET_TAG: "latest"
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  BUILD_URL: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
  NEON_TEST_IMAGE:  ${{vars.DOCKERHUB_ORG_NAME}}/neon_tests
  TF_VAR_run_number: ${{ github.run_number }}
  TF_VAR_ci_pp_solana_url: ${{secrets.DEVNET_INTERNAL_RPC}}
  TF_VAR_proxy_model_commit: ${{github.sha}}
  TF_VAR_neon_evm_commit: "latest"
  TF_VAR_faucet_model_commit: ${{vars.FAUCET_COMMIT}}
  TV_VAR_dockerhub_org_name: ${{vars.DOCKERHUB_ORG_NAME}}
  HCLOUD_TOKEN: ${{secrets.HCLOUD_TOKEN}}
  DOCKERHUB_ORG_NAME: ${{vars.DOCKERHUB_ORG_NAME}}
  FAUCET_COMMIT: ${{vars.FAUCET_COMMIT}}
  GH_ORG_NAME: ${{vars.GH_ORG_NAME}}
  IMAGE_NAME: ${{vars.IMAGE_NAME}}
  NEON_TEST_INVOKE_PROGRAM_IMAGE: ${{vars.NEON_TEST_INVOKE_PROGRAM_IMAGE}}
  NEON_TEST_RUN_LINK: ${{vars.NEON_TEST_RUN_LINK}}
  NEON_TESTS_ENDPOINT: ${{vars.NEON_TESTS_ENDPOINT}}
  TFSTATE_BUCKET: ${{vars.TFSTATE_BUCKET}}
  TFSTATE_KEY_PREFIX: ${{vars.TFSTATE_KEY_PREFIX}}
  TFSTATE_REGION: ${{vars.TFSTATE_REGION}}
  UNISWAP_V2_CORE_COMMIT: ${{vars.UNISWAP_V2_CORE_COMMIT}}
  UNISWAP_V2_CORE_REPO: ${{vars.UNISWAP_V2_CORE_REPO}}
  GITHUB_RUN_NUMBER: ${{ github.run_number }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}${{ github.event.inputs.neon_evm_commit }}
  cancel-in-progress: true
jobs:
  destroy-terraform:
    runs-on: test-runner
    steps:
      - name: Destroy terraform infrastructure
        env:
          TF_VAR_branch: ""
        run: |
          python3 ./.github/workflows/deploy.py destroy_terraform \
          --run_number=2632 \
          --proxy_tag=162a514266efbb6f99a66a3b66f62dc163cbef31-2c0a080c02
